// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project1_413.Models;

namespace Project1_413.Migrations
{
    [DbContext(typeof(taskContext))]
    partial class taskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Project1_413.Models.category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Category = "Home"
                        },
                        new
                        {
                            CategoryId = 2,
                            Category = "School"
                        },
                        new
                        {
                            CategoryId = 3,
                            Category = "Work"
                        },
                        new
                        {
                            CategoryId = 4,
                            Category = "Church"
                        });
                });

            modelBuilder.Entity("Project1_413.Models.taskResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("dueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("task")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("taskResponses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            completed = false,
                            dueDate = "2009-01-01",
                            quadrant = 1,
                            task = "test"
                        });
                });

            modelBuilder.Entity("Project1_413.Models.taskResponse", b =>
                {
                    b.HasOne("Project1_413.Models.category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
